name: Update Live Sources
on:
  schedule:
    - cron: '0 */24 * * *'  # 每6小时运行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install requests
    - run: python main.py
    - name: Commit changes
      run: |
        git config --local user.name "Auto Updater"
        git config --local user.email "actions@github.com"
        git add merged_channels.txt
        git commit -m "Auto update live sources" || echo "No changes"
        git push
